export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILURE = 'ADD_CLIENT_FAILURE';
export const ADD_CLIENT_STARTED = 'ADD_CLIENT_STARTED';

export const EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS';
export const EDIT_CLIENT_FAILURE = 'EDIT_CLIENT_FAILURE';
export const EDIT_CLIENT_STARTED = 'EDIT_CLIENT_STARTED';

export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAILURE = 'DELETE_CLIENT_FAILURE';
export const DELETE_CLIENT_STARTED = 'DELETE_CLIENT_STARTED';

export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAILURE = 'GET_CLIENTS_FAILURE';
export const GET_CLIENTS_STARTED = 'GET_CLIENTS_STARTED';



export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE';
export const ADD_ORDER_STARTED = 'ADD_ORDER_STARTED';

export const EDIT_ORDER_SUCCESS = 'EDIT_ORDER_SUCCESS';
export const EDIT_ORDER_FAILURE = 'EDIT_ORDER_FAILURE';
export const EDIT_ORDER_STARTED = 'EDIT_ORDER_STARTED';

export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';
export const DELETE_ORDER_STARTED = 'DELETE_ORDER_STARTED';

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';
export const GET_ORDERS_STARTED = 'GET_ORDERS_STARTED';



export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_FAILURE = 'ADD_ROOM_FAILURE';
export const ADD_ROOM_STARTED = 'ADD_ROOM_STARTED';

export const EDIT_ROOM_SUCCESS = 'EDIT_ROOM_SUCCESS';
export const EDIT_ROOM_FAILURE = 'EDIT_ROOM_FAILURE';
export const EDIT_ROOM_STARTED = 'EDIT_ROOM_STARTED';

export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAILURE = 'DELETE_ROOM_FAILURE';
export const DELETE_ROOM_STARTED = 'DELETE_ROOM_STARTED';

export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILURE = 'GET_ROOMS_FAILURE';
export const GET_ROOMS_STARTED = 'GET_ROOMS_STARTED';


